/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace WhisperChain {
  export type ConversationStruct = {
    participants: AddressLike[];
    conversationKey: BytesLike;
    createdAt: BigNumberish;
    isActive: boolean;
    messageCount: BigNumberish;
  };

  export type ConversationStructOutput = [
    participants: string[],
    conversationKey: string,
    createdAt: bigint,
    isActive: boolean,
    messageCount: bigint
  ] & {
    participants: string[];
    conversationKey: string;
    createdAt: bigint;
    isActive: boolean;
    messageCount: bigint;
  };

  export type MessageStruct = {
    sender: AddressLike;
    recipient: AddressLike;
    messageHash: BytesLike;
    timestamp: BigNumberish;
    delivered: boolean;
    read: boolean;
    paymentAmount: BigNumberish;
    paymentToken: AddressLike;
    ipfsHash: string;
    mediaType: BigNumberish;
    fileSize: BigNumberish;
  };

  export type MessageStructOutput = [
    sender: string,
    recipient: string,
    messageHash: string,
    timestamp: bigint,
    delivered: boolean,
    read: boolean,
    paymentAmount: bigint,
    paymentToken: string,
    ipfsHash: string,
    mediaType: bigint,
    fileSize: bigint
  ] & {
    sender: string;
    recipient: string;
    messageHash: string;
    timestamp: bigint;
    delivered: boolean;
    read: boolean;
    paymentAmount: bigint;
    paymentToken: string;
    ipfsHash: string;
    mediaType: bigint;
    fileSize: bigint;
  };
}

export interface WhisperChainInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MAX_FILE_SIZE"
      | "MAX_MESSAGES_PER_USER"
      | "MAX_STORAGE_PER_USER"
      | "clearStorage"
      | "conversations"
      | "createConversation"
      | "deleteMessage"
      | "emergencyWithdraw"
      | "getContractStats"
      | "getConversation"
      | "getFileSize"
      | "getIPFSHash"
      | "getMediaType"
      | "getMessage"
      | "getRemainingStorage"
      | "getUserMessageCount"
      | "getUserMessages"
      | "getUserPublicKey"
      | "getUserStorageUsed"
      | "isIPFSHashUsed"
      | "isMessageDeleted"
      | "isUserRegistered"
      | "markAsDelivered"
      | "markAsRead"
      | "messageDeleted"
      | "messages"
      | "owner"
      | "pause"
      | "paused"
      | "paymentSettled"
      | "registerUser"
      | "renounceOwnership"
      | "sendBatchMessages"
      | "sendMessage"
      | "transferOwnership"
      | "unpause"
      | "updateLastSeen"
      | "updatePublicKey"
      | "usedIPFSHashes"
      | "userBalances"
      | "userConversations"
      | "userMessageCount"
      | "userMessages"
      | "userProfiles"
      | "userStorageUsed"
      | "withdrawBalance"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BatchMessageSent"
      | "ConversationCreated"
      | "MediaUploaded"
      | "MessageDeleted"
      | "MessageDelivered"
      | "MessageRead"
      | "MessageSent"
      | "OwnershipTransferred"
      | "Paused"
      | "PaymentSettled"
      | "StorageLimitExceeded"
      | "Unpaused"
      | "UserRegistered"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MAX_FILE_SIZE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_MESSAGES_PER_USER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_STORAGE_PER_USER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "clearStorage",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "conversations",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createConversation",
    values: [AddressLike[], BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deleteMessage",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getContractStats",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getConversation",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getFileSize",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getIPFSHash",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMediaType",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMessage",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRemainingStorage",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserMessageCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserMessages",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserPublicKey",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserStorageUsed",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isIPFSHashUsed",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "isMessageDeleted",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isUserRegistered",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "markAsDelivered",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "markAsRead",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "messageDeleted",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "messages", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "paymentSettled",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerUser",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "sendBatchMessages",
    values: [
      AddressLike[],
      BytesLike[],
      AddressLike[],
      BigNumberish[],
      string[],
      BigNumberish[],
      BigNumberish[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "sendMessage",
    values: [
      AddressLike,
      BytesLike,
      AddressLike,
      BigNumberish,
      string,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateLastSeen",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updatePublicKey",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "usedIPFSHashes",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "userBalances",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userConversations",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userMessageCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userMessages",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userProfiles",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userStorageUsed",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawBalance",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "MAX_FILE_SIZE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_MESSAGES_PER_USER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_STORAGE_PER_USER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "clearStorage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "conversations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createConversation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deleteMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContractStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getConversation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFileSize",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getIPFSHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMediaType",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getMessage", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRemainingStorage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserMessageCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserMessages",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserPublicKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserStorageUsed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isIPFSHashUsed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isMessageDeleted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isUserRegistered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "markAsDelivered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "markAsRead", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "messageDeleted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "messages", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "paymentSettled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sendBatchMessages",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sendMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateLastSeen",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updatePublicKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "usedIPFSHashes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userBalances",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userConversations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userMessageCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userMessages",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userProfiles",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userStorageUsed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawBalance",
    data: BytesLike
  ): Result;
}

export namespace BatchMessageSentEvent {
  export type InputTuple = [messageIds: BytesLike[], sender: AddressLike];
  export type OutputTuple = [messageIds: string[], sender: string];
  export interface OutputObject {
    messageIds: string[];
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ConversationCreatedEvent {
  export type InputTuple = [
    conversationId: BytesLike,
    participants: AddressLike[]
  ];
  export type OutputTuple = [conversationId: string, participants: string[]];
  export interface OutputObject {
    conversationId: string;
    participants: string[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MediaUploadedEvent {
  export type InputTuple = [
    messageId: BytesLike,
    ipfsHash: string,
    mediaType: BigNumberish
  ];
  export type OutputTuple = [
    messageId: string,
    ipfsHash: string,
    mediaType: bigint
  ];
  export interface OutputObject {
    messageId: string;
    ipfsHash: string;
    mediaType: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MessageDeletedEvent {
  export type InputTuple = [messageId: BytesLike, deleter: AddressLike];
  export type OutputTuple = [messageId: string, deleter: string];
  export interface OutputObject {
    messageId: string;
    deleter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MessageDeliveredEvent {
  export type InputTuple = [messageId: BytesLike, timestamp: BigNumberish];
  export type OutputTuple = [messageId: string, timestamp: bigint];
  export interface OutputObject {
    messageId: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MessageReadEvent {
  export type InputTuple = [messageId: BytesLike, timestamp: BigNumberish];
  export type OutputTuple = [messageId: string, timestamp: bigint];
  export interface OutputObject {
    messageId: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MessageSentEvent {
  export type InputTuple = [
    messageId: BytesLike,
    sender: AddressLike,
    recipient: AddressLike,
    timestamp: BigNumberish,
    paymentAmount: BigNumberish
  ];
  export type OutputTuple = [
    messageId: string,
    sender: string,
    recipient: string,
    timestamp: bigint,
    paymentAmount: bigint
  ];
  export interface OutputObject {
    messageId: string;
    sender: string;
    recipient: string;
    timestamp: bigint;
    paymentAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentSettledEvent {
  export type InputTuple = [messageId: BytesLike, amount: BigNumberish];
  export type OutputTuple = [messageId: string, amount: bigint];
  export interface OutputObject {
    messageId: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StorageLimitExceededEvent {
  export type InputTuple = [
    user: AddressLike,
    used: BigNumberish,
    limit: BigNumberish
  ];
  export type OutputTuple = [user: string, used: bigint, limit: bigint];
  export interface OutputObject {
    user: string;
    used: bigint;
    limit: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserRegisteredEvent {
  export type InputTuple = [user: AddressLike, publicKey: BytesLike];
  export type OutputTuple = [user: string, publicKey: string];
  export interface OutputObject {
    user: string;
    publicKey: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface WhisperChain extends BaseContract {
  connect(runner?: ContractRunner | null): WhisperChain;
  waitForDeployment(): Promise<this>;

  interface: WhisperChainInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MAX_FILE_SIZE: TypedContractMethod<[], [bigint], "view">;

  MAX_MESSAGES_PER_USER: TypedContractMethod<[], [bigint], "view">;

  MAX_STORAGE_PER_USER: TypedContractMethod<[], [bigint], "view">;

  clearStorage: TypedContractMethod<[], [void], "nonpayable">;

  conversations: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, boolean, bigint] & {
        conversationKey: string;
        createdAt: bigint;
        isActive: boolean;
        messageCount: bigint;
      }
    ],
    "view"
  >;

  createConversation: TypedContractMethod<
    [participants: AddressLike[], conversationKeyHash: BytesLike],
    [void],
    "nonpayable"
  >;

  deleteMessage: TypedContractMethod<
    [messageId: BytesLike],
    [void],
    "nonpayable"
  >;

  emergencyWithdraw: TypedContractMethod<[], [void], "nonpayable">;

  getContractStats: TypedContractMethod<[], [[bigint, bigint, bigint]], "view">;

  getConversation: TypedContractMethod<
    [conversationId: BytesLike],
    [WhisperChain.ConversationStructOutput],
    "view"
  >;

  getFileSize: TypedContractMethod<[messageId: BytesLike], [bigint], "view">;

  getIPFSHash: TypedContractMethod<[messageId: BytesLike], [string], "view">;

  getMediaType: TypedContractMethod<[messageId: BytesLike], [bigint], "view">;

  getMessage: TypedContractMethod<
    [messageId: BytesLike],
    [WhisperChain.MessageStructOutput],
    "view"
  >;

  getRemainingStorage: TypedContractMethod<
    [user: AddressLike],
    [bigint],
    "view"
  >;

  getUserMessageCount: TypedContractMethod<
    [user: AddressLike],
    [bigint],
    "view"
  >;

  getUserMessages: TypedContractMethod<[user: AddressLike], [string[]], "view">;

  getUserPublicKey: TypedContractMethod<[user: AddressLike], [string], "view">;

  getUserStorageUsed: TypedContractMethod<
    [user: AddressLike],
    [bigint],
    "view"
  >;

  isIPFSHashUsed: TypedContractMethod<[ipfsHash: string], [boolean], "view">;

  isMessageDeleted: TypedContractMethod<
    [messageId: BytesLike],
    [boolean],
    "view"
  >;

  isUserRegistered: TypedContractMethod<[user: AddressLike], [boolean], "view">;

  markAsDelivered: TypedContractMethod<
    [messageId: BytesLike],
    [void],
    "nonpayable"
  >;

  markAsRead: TypedContractMethod<[messageId: BytesLike], [void], "nonpayable">;

  messageDeleted: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  messages: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        bigint,
        boolean,
        boolean,
        bigint,
        string,
        string,
        bigint,
        bigint
      ] & {
        sender: string;
        recipient: string;
        messageHash: string;
        timestamp: bigint;
        delivered: boolean;
        read: boolean;
        paymentAmount: bigint;
        paymentToken: string;
        ipfsHash: string;
        mediaType: bigint;
        fileSize: bigint;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  paymentSettled: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  registerUser: TypedContractMethod<
    [publicKey: BytesLike, username: string],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  sendBatchMessages: TypedContractMethod<
    [
      recipients: AddressLike[],
      messageHashes: BytesLike[],
      paymentTokens: AddressLike[],
      paymentAmounts: BigNumberish[],
      ipfsHashes: string[],
      mediaTypes: BigNumberish[],
      fileSizes: BigNumberish[]
    ],
    [void],
    "payable"
  >;

  sendMessage: TypedContractMethod<
    [
      recipient: AddressLike,
      messageHash: BytesLike,
      paymentToken: AddressLike,
      paymentAmount: BigNumberish,
      ipfsHash: string,
      mediaType: BigNumberish,
      fileSize: BigNumberish
    ],
    [void],
    "payable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  updateLastSeen: TypedContractMethod<[], [void], "nonpayable">;

  updatePublicKey: TypedContractMethod<
    [newPublicKey: BytesLike],
    [void],
    "nonpayable"
  >;

  usedIPFSHashes: TypedContractMethod<[arg0: string], [boolean], "view">;

  userBalances: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  userConversations: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  userMessageCount: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  userMessages: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  userProfiles: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, boolean, bigint, string] & {
        publicKey: string;
        isActive: boolean;
        lastSeen: bigint;
        username: string;
      }
    ],
    "view"
  >;

  userStorageUsed: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  withdrawBalance: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MAX_FILE_SIZE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_MESSAGES_PER_USER"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_STORAGE_PER_USER"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "clearStorage"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "conversations"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, boolean, bigint] & {
        conversationKey: string;
        createdAt: bigint;
        isActive: boolean;
        messageCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "createConversation"
  ): TypedContractMethod<
    [participants: AddressLike[], conversationKeyHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deleteMessage"
  ): TypedContractMethod<[messageId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getContractStats"
  ): TypedContractMethod<[], [[bigint, bigint, bigint]], "view">;
  getFunction(
    nameOrSignature: "getConversation"
  ): TypedContractMethod<
    [conversationId: BytesLike],
    [WhisperChain.ConversationStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getFileSize"
  ): TypedContractMethod<[messageId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getIPFSHash"
  ): TypedContractMethod<[messageId: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getMediaType"
  ): TypedContractMethod<[messageId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getMessage"
  ): TypedContractMethod<
    [messageId: BytesLike],
    [WhisperChain.MessageStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRemainingStorage"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserMessageCount"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserMessages"
  ): TypedContractMethod<[user: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getUserPublicKey"
  ): TypedContractMethod<[user: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getUserStorageUsed"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "isIPFSHashUsed"
  ): TypedContractMethod<[ipfsHash: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "isMessageDeleted"
  ): TypedContractMethod<[messageId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isUserRegistered"
  ): TypedContractMethod<[user: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "markAsDelivered"
  ): TypedContractMethod<[messageId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "markAsRead"
  ): TypedContractMethod<[messageId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "messageDeleted"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "messages"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        bigint,
        boolean,
        boolean,
        bigint,
        string,
        string,
        bigint,
        bigint
      ] & {
        sender: string;
        recipient: string;
        messageHash: string;
        timestamp: bigint;
        delivered: boolean;
        read: boolean;
        paymentAmount: bigint;
        paymentToken: string;
        ipfsHash: string;
        mediaType: bigint;
        fileSize: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "paymentSettled"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "registerUser"
  ): TypedContractMethod<
    [publicKey: BytesLike, username: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "sendBatchMessages"
  ): TypedContractMethod<
    [
      recipients: AddressLike[],
      messageHashes: BytesLike[],
      paymentTokens: AddressLike[],
      paymentAmounts: BigNumberish[],
      ipfsHashes: string[],
      mediaTypes: BigNumberish[],
      fileSizes: BigNumberish[]
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "sendMessage"
  ): TypedContractMethod<
    [
      recipient: AddressLike,
      messageHash: BytesLike,
      paymentToken: AddressLike,
      paymentAmount: BigNumberish,
      ipfsHash: string,
      mediaType: BigNumberish,
      fileSize: BigNumberish
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateLastSeen"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updatePublicKey"
  ): TypedContractMethod<[newPublicKey: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usedIPFSHashes"
  ): TypedContractMethod<[arg0: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "userBalances"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "userConversations"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "userMessageCount"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "userMessages"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "userProfiles"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, boolean, bigint, string] & {
        publicKey: string;
        isActive: boolean;
        lastSeen: bigint;
        username: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "userStorageUsed"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "withdrawBalance"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "BatchMessageSent"
  ): TypedContractEvent<
    BatchMessageSentEvent.InputTuple,
    BatchMessageSentEvent.OutputTuple,
    BatchMessageSentEvent.OutputObject
  >;
  getEvent(
    key: "ConversationCreated"
  ): TypedContractEvent<
    ConversationCreatedEvent.InputTuple,
    ConversationCreatedEvent.OutputTuple,
    ConversationCreatedEvent.OutputObject
  >;
  getEvent(
    key: "MediaUploaded"
  ): TypedContractEvent<
    MediaUploadedEvent.InputTuple,
    MediaUploadedEvent.OutputTuple,
    MediaUploadedEvent.OutputObject
  >;
  getEvent(
    key: "MessageDeleted"
  ): TypedContractEvent<
    MessageDeletedEvent.InputTuple,
    MessageDeletedEvent.OutputTuple,
    MessageDeletedEvent.OutputObject
  >;
  getEvent(
    key: "MessageDelivered"
  ): TypedContractEvent<
    MessageDeliveredEvent.InputTuple,
    MessageDeliveredEvent.OutputTuple,
    MessageDeliveredEvent.OutputObject
  >;
  getEvent(
    key: "MessageRead"
  ): TypedContractEvent<
    MessageReadEvent.InputTuple,
    MessageReadEvent.OutputTuple,
    MessageReadEvent.OutputObject
  >;
  getEvent(
    key: "MessageSent"
  ): TypedContractEvent<
    MessageSentEvent.InputTuple,
    MessageSentEvent.OutputTuple,
    MessageSentEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "PaymentSettled"
  ): TypedContractEvent<
    PaymentSettledEvent.InputTuple,
    PaymentSettledEvent.OutputTuple,
    PaymentSettledEvent.OutputObject
  >;
  getEvent(
    key: "StorageLimitExceeded"
  ): TypedContractEvent<
    StorageLimitExceededEvent.InputTuple,
    StorageLimitExceededEvent.OutputTuple,
    StorageLimitExceededEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;
  getEvent(
    key: "UserRegistered"
  ): TypedContractEvent<
    UserRegisteredEvent.InputTuple,
    UserRegisteredEvent.OutputTuple,
    UserRegisteredEvent.OutputObject
  >;

  filters: {
    "BatchMessageSent(bytes32[],address)": TypedContractEvent<
      BatchMessageSentEvent.InputTuple,
      BatchMessageSentEvent.OutputTuple,
      BatchMessageSentEvent.OutputObject
    >;
    BatchMessageSent: TypedContractEvent<
      BatchMessageSentEvent.InputTuple,
      BatchMessageSentEvent.OutputTuple,
      BatchMessageSentEvent.OutputObject
    >;

    "ConversationCreated(bytes32,address[])": TypedContractEvent<
      ConversationCreatedEvent.InputTuple,
      ConversationCreatedEvent.OutputTuple,
      ConversationCreatedEvent.OutputObject
    >;
    ConversationCreated: TypedContractEvent<
      ConversationCreatedEvent.InputTuple,
      ConversationCreatedEvent.OutputTuple,
      ConversationCreatedEvent.OutputObject
    >;

    "MediaUploaded(bytes32,string,uint8)": TypedContractEvent<
      MediaUploadedEvent.InputTuple,
      MediaUploadedEvent.OutputTuple,
      MediaUploadedEvent.OutputObject
    >;
    MediaUploaded: TypedContractEvent<
      MediaUploadedEvent.InputTuple,
      MediaUploadedEvent.OutputTuple,
      MediaUploadedEvent.OutputObject
    >;

    "MessageDeleted(bytes32,address)": TypedContractEvent<
      MessageDeletedEvent.InputTuple,
      MessageDeletedEvent.OutputTuple,
      MessageDeletedEvent.OutputObject
    >;
    MessageDeleted: TypedContractEvent<
      MessageDeletedEvent.InputTuple,
      MessageDeletedEvent.OutputTuple,
      MessageDeletedEvent.OutputObject
    >;

    "MessageDelivered(bytes32,uint256)": TypedContractEvent<
      MessageDeliveredEvent.InputTuple,
      MessageDeliveredEvent.OutputTuple,
      MessageDeliveredEvent.OutputObject
    >;
    MessageDelivered: TypedContractEvent<
      MessageDeliveredEvent.InputTuple,
      MessageDeliveredEvent.OutputTuple,
      MessageDeliveredEvent.OutputObject
    >;

    "MessageRead(bytes32,uint256)": TypedContractEvent<
      MessageReadEvent.InputTuple,
      MessageReadEvent.OutputTuple,
      MessageReadEvent.OutputObject
    >;
    MessageRead: TypedContractEvent<
      MessageReadEvent.InputTuple,
      MessageReadEvent.OutputTuple,
      MessageReadEvent.OutputObject
    >;

    "MessageSent(bytes32,address,address,uint256,uint256)": TypedContractEvent<
      MessageSentEvent.InputTuple,
      MessageSentEvent.OutputTuple,
      MessageSentEvent.OutputObject
    >;
    MessageSent: TypedContractEvent<
      MessageSentEvent.InputTuple,
      MessageSentEvent.OutputTuple,
      MessageSentEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "PaymentSettled(bytes32,uint256)": TypedContractEvent<
      PaymentSettledEvent.InputTuple,
      PaymentSettledEvent.OutputTuple,
      PaymentSettledEvent.OutputObject
    >;
    PaymentSettled: TypedContractEvent<
      PaymentSettledEvent.InputTuple,
      PaymentSettledEvent.OutputTuple,
      PaymentSettledEvent.OutputObject
    >;

    "StorageLimitExceeded(address,uint256,uint256)": TypedContractEvent<
      StorageLimitExceededEvent.InputTuple,
      StorageLimitExceededEvent.OutputTuple,
      StorageLimitExceededEvent.OutputObject
    >;
    StorageLimitExceeded: TypedContractEvent<
      StorageLimitExceededEvent.InputTuple,
      StorageLimitExceededEvent.OutputTuple,
      StorageLimitExceededEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;

    "UserRegistered(address,bytes32)": TypedContractEvent<
      UserRegisteredEvent.InputTuple,
      UserRegisteredEvent.OutputTuple,
      UserRegisteredEvent.OutputObject
    >;
    UserRegistered: TypedContractEvent<
      UserRegisteredEvent.InputTuple,
      UserRegisteredEvent.OutputTuple,
      UserRegisteredEvent.OutputObject
    >;
  };
}
